<?php

namespace Database\Seeders;

use App\Models\Brand;
use App\Models\Category;
use App\Models\Product;
use Illuminate\Database\Seeder;
use Illuminate\Support\Str;

class ProductSeeder extends Seeder
{
    public function run(): void
    {
        $category = Category::query()->first();
        $categoriesBySlug = Category::query()
            ->whereIn('slug', [
                'mens-fashion',
                'womens-fashion',
                'accessories',
                'footwear',
                'bags-purses',
                'eyewear',
                'watches',
                'jewelry',
            ])
            ->get()
            ->keyBy('slug');

        $getCategoryId = static fn (string $slug) => $categoriesBySlug->get($slug)?->id ?? $category?->id;

        $fashionHubBrand = Brand::query()->where('slug', 'fashionhub-premium')->first();
        $urbanBrand = Brand::query()->where('slug', 'urban-style')->first();
        $classicWearBrand = Brand::query()->where('slug', 'classic-wear')->first();

        $variantProduct = Product::query()->updateOrCreate(
            ['slug' => 'classic-crew-tee'],
            [
                'name' => 'Classic Crew Tee',
                'short_description' => 'A soft everyday tee with generated size and style variants.',
                'description' => 'This classic cotton crew tee is set up as a multi-variation product that stores attributes and variants directly in the products table as JSON.',
                'category_id' => $category?->id,
                'brand_id' => $fashionHubBrand?->id,
                'status' => 'active',
                'is_featured' => true,
                'sales_count' => 320,
                'rating' => 4.80,
                'has_variants' => true,
                'base_price' => 1200,
                'sale_price' => 999,
                'stock' => 0,
                'attributes' => [
                    [
                        'name' => 'Size',
                        'slug' => 'size',
                        'display_type' => 'text',
                        'values' => [
                            ['label' => 'Small', 'value' => 'S'],
                            ['label' => 'Medium', 'value' => 'M'],
                        ],
                    ],
                    [
                        'name' => 'Style',
                        'slug' => 'style',
                        'display_type' => 'image',
                        'values' => [
                            ['label' => 'Black', 'value' => 'black', 'image' => null],
                            ['label' => 'Stone', 'value' => 'stone', 'image' => null],
                        ],
                    ],
                ],
                'seo' => [
                    'meta_title' => 'Classic Crew Tee | Fashion Hub',
                    'meta_description' => 'A variant-ready crew neck tee with size and style combinations stored in JSON.',
                    'meta_keywords' => 'crew tee, cotton t-shirt, variant product',
                    'canonical_url' => 'https://fashionhub.test/products/classic-crew-tee',
                ],
            ],
        );

        $variantProduct->variants = collect($variantProduct->generateVariantsFromAttributes())
            ->map(function (array $variant, int $index): array {
                $variant['price'] = 1200 + ($index * 50);
                $variant['sale_price'] = $index === 0 ? 999 : null;
                $variant['stock'] = 10 - ($index * 2);
                $variant['low_stock_alert'] = 2;
                $variant['status'] = 'active';
                $variant['is_default'] = $index === 0;

                return $variant;
            })
            ->all();
        $variantProduct->save();

        Product::query()->updateOrCreate(
            ['slug' => 'minimal-linen-shirt'],
            [
                'name' => 'Minimal Linen Shirt',
                'short_description' => 'Simple product example without variant-level inventory.',
                'description' => 'A clean simple product record using base price and stock at the product level.',
                'category_id' => $category?->id,
                'brand_id' => $urbanBrand?->id,
                'status' => 'active',
                'is_featured' => false,
                'sales_count' => 95,
                'rating' => 4.20,
                'has_variants' => false,
                'base_price' => 1850,
                'sale_price' => 1650,
                'stock' => 24,
                'seo' => [
                    'meta_title' => 'Minimal Linen Shirt | Fashion Hub',
                    'meta_description' => 'Simple product example seeded with product-level pricing and stock.',
                ],
            ],
        );

        $products = [
            [
                'name' => 'Elegant Summer Dress',
                'short_description' => 'Breezy, elegant dress ideal for summer events and daytime wear.',
                'description' => 'A lightweight and graceful summer dress designed for comfort and style throughout the day.',
                'category_slug' => 'womens-fashion',
                'brand_id' => $fashionHubBrand?->id,
                'featured_image' => 'https://images.unsplash.com/photo-1591047139829-d91aecb6caea?w=400',
                'base_price' => 159.99,
                'sale_price' => 129.99,
                'stock' => 34,
                'is_featured' => true,
                'sales_count' => 520,
                'rating' => 4.90,
                'meta_keywords' => 'summer dress, women fashion, elegant dress',
            ],
            [
                'name' => 'Casual Denim Jacket',
                'short_description' => 'Timeless denim jacket with a clean casual fit.',
                'description' => 'A versatile denim jacket that pairs easily with everyday outfits across seasons.',
                'category_slug' => 'mens-fashion',
                'brand_id' => $urbanBrand?->id,
                'featured_image' => 'https://images.unsplash.com/photo-1602810318383-e386cc2a3ccf?w=400',
                'base_price' => 89.99,
                'sale_price' => null,
                'stock' => 28,
                'is_featured' => false,
                'sales_count' => 215,
                'rating' => 4.30,
                'meta_keywords' => 'denim jacket, men fashion, casual jacket',
            ],
            [
                'name' => 'Classic White Sneakers',
                'short_description' => 'Daily-wear white sneakers with clean minimal design.',
                'description' => 'Classic sneakers built for comfort and style, suitable for casual and semi-casual looks.',
                'category_slug' => 'footwear',
                'brand_id' => $classicWearBrand?->id,
                'featured_image' => 'https://images.unsplash.com/photo-1596755094514-f87e34085b2c?w=400',
                'base_price' => 79.99,
                'sale_price' => null,
                'stock' => 40,
                'is_featured' => false,
                'sales_count' => 480,
                'rating' => 4.60,
                'meta_keywords' => 'white sneakers, footwear, casual shoes',
            ],
            [
                'name' => 'Designer Handbag',
                'short_description' => 'Premium handbag with modern silhouette and utility.',
                'description' => 'An elevated handbag designed to add a refined touch while carrying essentials with ease.',
                'category_slug' => 'bags-purses',
                'brand_id' => $fashionHubBrand?->id,
                'featured_image' => 'https://images.unsplash.com/photo-1611312449408-fcece27cdbb7?w=400',
                'base_price' => 199.99,
                'sale_price' => null,
                'stock' => 16,
                'is_featured' => true,
                'sales_count' => 310,
                'rating' => 4.75,
                'meta_keywords' => 'designer handbag, women bags, premium purse',
            ],
            [
                'name' => 'Slim Fit Blazer',
                'short_description' => 'Structured blazer with modern slim-fit cut.',
                'description' => 'A polished blazer tailored for formal meetings, events, and smart-casual styling.',
                'category_slug' => 'mens-fashion',
                'brand_id' => $classicWearBrand?->id,
                'featured_image' => 'https://images.unsplash.com/photo-1620799140408-edc6dcb6d633?w=400',
                'base_price' => 149.99,
                'sale_price' => null,
                'stock' => 22,
                'is_featured' => true,
                'sales_count' => 180,
                'rating' => 4.50,
                'meta_keywords' => 'slim blazer, men formal wear, blazer',
            ],
            [
                'name' => 'Leather Boots',
                'short_description' => 'Durable leather boots for everyday confidence.',
                'description' => 'Premium leather boots offering sturdy comfort and a timeless look.',
                'category_slug' => 'footwear',
                'brand_id' => $urbanBrand?->id,
                'featured_image' => 'https://images.unsplash.com/photo-1617019114583-affb34d1b3cd?w=400',
                'base_price' => 169.99,
                'sale_price' => null,
                'stock' => 19,
                'is_featured' => false,
                'sales_count' => 140,
                'rating' => 4.40,
                'meta_keywords' => 'leather boots, boots, men footwear',
            ],
            [
                'name' => 'Casual T-Shirt',
                'short_description' => 'Soft cotton tee for everyday casual style.',
                'description' => 'A breathable casual t-shirt made for comfort with a relaxed fit.',
                'category_slug' => 'mens-fashion',
                'brand_id' => $urbanBrand?->id,
                'featured_image' => 'https://images.unsplash.com/photo-1618354691373-d851c5c3a990?w=400',
                'base_price' => 39.99,
                'sale_price' => null,
                'stock' => 60,
                'is_featured' => false,
                'sales_count' => 650,
                'rating' => 4.10,
                'meta_keywords' => 'casual tshirt, men t-shirt, basics',
            ],
            [
                'name' => 'Stylish Sunglasses',
                'short_description' => 'Fashion-forward sunglasses with modern frames.',
                'description' => 'Stylish eyewear that balances UV protection with trend-conscious design.',
                'category_slug' => 'eyewear',
                'brand_id' => $classicWearBrand?->id,
                'featured_image' => 'https://images.unsplash.com/photo-1611652022419-a9419f74343d?w=400',
                'base_price' => 59.99,
                'sale_price' => null,
                'stock' => 32,
                'is_featured' => false,
                'sales_count' => 290,
                'rating' => 4.35,
                'meta_keywords' => 'sunglasses, eyewear, stylish glasses',
            ],
            [
                'name' => 'Leather Wallet',
                'short_description' => 'Compact leather wallet with premium finish.',
                'description' => 'A functional wallet crafted from quality leather for daily essentials.',
                'category_slug' => 'accessories',
                'brand_id' => $fashionHubBrand?->id,
                'featured_image' => 'https://images.unsplash.com/photo-1460353581641-37baddab0fa2?w=400',
                'base_price' => 49.99,
                'sale_price' => null,
                'stock' => 45,
                'is_featured' => false,
                'sales_count' => 410,
                'rating' => 4.25,
                'meta_keywords' => 'wallet, leather wallet, accessories',
            ],
            [
                'name' => 'Striped Sweater',
                'short_description' => 'Cozy striped sweater for cool-weather layering.',
                'description' => 'A soft-knit striped sweater perfect for relaxed styling and seasonal layering.',
                'category_slug' => 'womens-fashion',
                'brand_id' => $classicWearBrand?->id,
                'featured_image' => 'https://images.unsplash.com/photo-1603252109303-2751441dd157?w=400',
                'base_price' => 99.99,
                'sale_price' => 69.99,
                'stock' => 24,
                'is_featured' => false,
                'sales_count' => 175,
                'rating' => 4.20,
                'meta_keywords' => 'striped sweater, knitwear, fashion sweater',
            ],
            [
                'name' => 'Vintage Watch',
                'short_description' => 'Classic timepiece inspired by vintage styling.',
                'description' => 'A refined vintage watch designed with elegant details and durable build quality.',
                'category_slug' => 'watches',
                'brand_id' => $fashionHubBrand?->id,
                'featured_image' => 'https://images.unsplash.com/photo-1539533018447-63fcce2678e3?w=400',
                'base_price' => 249.99,
                'sale_price' => null,
                'stock' => 14,
                'is_featured' => true,
                'sales_count' => 230,
                'rating' => 4.85,
                'meta_keywords' => 'vintage watch, wrist watch, accessories',
            ],
            [
                'name' => 'Formal Trousers',
                'short_description' => 'Tailored trousers for office and formal occasions.',
                'description' => 'Smart formal trousers with clean tailoring and all-day comfort.',
                'category_slug' => 'mens-fashion',
                'brand_id' => $classicWearBrand?->id,
                'featured_image' => 'https://images.unsplash.com/photo-1600185365926-3a2ce3cdb9eb?w=400',
                'base_price' => 99.99,
                'sale_price' => null,
                'stock' => 27,
                'is_featured' => false,
                'sales_count' => 120,
                'rating' => 4.15,
                'meta_keywords' => 'formal trousers, men pants, office wear',
            ],
            [
                'name' => 'Floral Maxi Dress',
                'short_description' => 'Flowy maxi dress with elegant floral print.',
                'description' => 'A statement floral maxi dress ideal for outings, brunch, and festive moments.',
                'category_slug' => 'womens-fashion',
                'brand_id' => $fashionHubBrand?->id,
                'featured_image' => 'https://images.unsplash.com/photo-1515372039744-b8f02a3ae446?w=400',
                'base_price' => 159.99,
                'sale_price' => null,
                'stock' => 18,
                'is_featured' => true,
                'sales_count' => 385,
                'rating' => 4.70,
                'meta_keywords' => 'maxi dress, floral dress, women clothing',
            ],
            [
                'name' => 'Striped Polo Shirt',
                'short_description' => 'Smart-casual striped polo with breathable fabric.',
                'description' => 'A versatile striped polo shirt crafted for polished casual wear.',
                'category_slug' => 'mens-fashion',
                'brand_id' => $urbanBrand?->id,
                'featured_image' => 'https://images.unsplash.com/photo-1594633313593-bab3825d0caf?w=400',
                'base_price' => 69.99,
                'sale_price' => null,
                'stock' => 36,
                'is_featured' => false,
                'sales_count' => 260,
                'rating' => 4.00,
                'meta_keywords' => 'polo shirt, striped shirt, men casual',
            ],
            [
                'name' => 'Leather Crossbody',
                'short_description' => 'Compact crossbody bag in premium leather.',
                'description' => 'A practical and stylish leather crossbody designed for daily essentials.',
                'category_slug' => 'bags-purses',
                'brand_id' => $fashionHubBrand?->id,
                'featured_image' => 'https://images.unsplash.com/photo-1560343090-f0409e92791a?w=400',
                'base_price' => 189.99,
                'sale_price' => null,
                'stock' => 20,
                'is_featured' => false,
                'sales_count' => 195,
                'rating' => 4.55,
                'meta_keywords' => 'crossbody bag, leather bag, women accessories',
            ],
            [
                'name' => 'Athletic Sneakers',
                'short_description' => 'Comfort-focused sneakers for active days.',
                'description' => 'Athletic sneakers that combine cushioned comfort with contemporary sporty style.',
                'category_slug' => 'footwear',
                'brand_id' => $urbanBrand?->id,
                'featured_image' => 'https://images.unsplash.com/photo-1608231387042-66d1773070a5?w=400',
                'base_price' => 119.99,
                'sale_price' => null,
                'stock' => 26,
                'is_featured' => false,
                'sales_count' => 340,
                'rating' => 4.45,
                'meta_keywords' => 'athletic sneakers, sport shoes, footwear',
            ],
            [
                'name' => 'Wool Overcoat',
                'short_description' => 'Warm overcoat with classic tailored silhouette.',
                'description' => 'A premium wool overcoat designed for winter elegance and lasting comfort.',
                'category_slug' => 'mens-fashion',
                'brand_id' => $classicWearBrand?->id,
                'featured_image' => 'https://images.unsplash.com/photo-1434389677669-e08b4cac3105?w=400',
                'base_price' => 249.99,
                'sale_price' => null,
                'stock' => 15,
                'is_featured' => true,
                'sales_count' => 155,
                'rating' => 4.65,
                'meta_keywords' => 'wool overcoat, men coat, winter fashion',
            ],
            [
                'name' => 'Graphic Hoodie',
                'short_description' => 'Street-style hoodie with soft brushed interior.',
                'description' => 'A relaxed-fit graphic hoodie built for everyday comfort and layered looks.',
                'category_slug' => 'mens-fashion',
                'brand_id' => $urbanBrand?->id,
                'featured_image' => 'https://images.unsplash.com/photo-1572635196237-14b3f281503f?w=400',
                'base_price' => 89.99,
                'sale_price' => null,
                'stock' => 31,
                'is_featured' => false,
                'sales_count' => 275,
                'rating' => 4.05,
                'meta_keywords' => 'graphic hoodie, hoodie, streetwear',
            ],
            [
                'name' => 'Smart Watch',
                'short_description' => 'Feature-packed smartwatch for modern lifestyle.',
                'description' => 'A sleek smartwatch offering everyday fitness, notifications, and style.',
                'category_slug' => 'watches',
                'brand_id' => $fashionHubBrand?->id,
                'featured_image' => 'https://images.unsplash.com/photo-1551028719-00167b16eac5?w=400',
                'base_price' => 299.99,
                'sale_price' => null,
                'stock' => 12,
                'is_featured' => true,
                'sales_count' => 430,
                'rating' => 4.95,
                'meta_keywords' => 'smart watch, wearable tech, modern watch',
            ],
            [
                'name' => 'Aviator Sunglasses',
                'short_description' => 'Classic aviator frame with modern finish.',
                'description' => 'Timeless aviator sunglasses built for comfort, clarity, and statement style.',
                'category_slug' => 'eyewear',
                'brand_id' => $classicWearBrand?->id,
                'featured_image' => 'https://images.unsplash.com/photo-1506629082955-511b1aa562c8?w=400',
                'base_price' => 99.99,
                'sale_price' => null,
                'stock' => 29,
                'is_featured' => false,
                'sales_count' => 200,
                'rating' => 4.30,
                'meta_keywords' => 'aviator sunglasses, eyewear, shades',
            ],
        ];

        foreach ($products as $productData) {
            $slug = Str::slug($productData['name']);

            Product::query()->updateOrCreate(
                ['slug' => $slug],
                [
                    'name' => $productData['name'],
                    'slug' => $slug,
                    'short_description' => $productData['short_description'],
                    'description' => $productData['description'],
                    'category_id' => $getCategoryId($productData['category_slug']),
                    'brand_id' => $productData['brand_id'],
                    'status' => 'active',
                    'featured_image' => $productData['featured_image'],
                    'is_featured' => $productData['is_featured'] ?? false,
                    'sales_count' => $productData['sales_count'] ?? 0,
                    'rating' => $productData['rating'] ?? 0,
                    'has_variants' => false,
                    'base_price' => $productData['base_price'],
                    'sale_price' => $productData['sale_price'],
                    'stock' => $productData['stock'],
                    'seo' => [
                        'meta_title' => $productData['name'].' | Fashion Hub',
                        'meta_description' => $productData['short_description'],
                        'meta_keywords' => $productData['meta_keywords'],
                        'canonical_url' => 'https://fashionhub.test/products/'.$slug,
                    ],
                ],
            );
        }
    }
}
